### ISSUE TITLE
Not able to run any query  (SELEC 1)- getting timeout exception ( using via SQLWorkbench)

### ISSUE THREAD

**Issue by ssenathi** [burtcorp/athena-jdbc#3]
2019-09-02 21:15:20 ERROR DbMetadata.getCatalogInformation() Error retrieving catalog information Not implemented
java.lang.UnsupportedOperationException: Not implemented
        at io.burt.athena.AthenaDatabaseMetaData.getCatalogs(AthenaDatabaseMetaData.java:667)
        at workbench.db.DbMetadata.getCatalogInformation(DbMetadata.java:2685)
        at workbench.gui.dbobjects.objecttree.TreeLoader.loadCatalogs(TreeLoader.java:455)
        at workbench.gui.dbobjects.objecttree.TreeLoader.load(TreeLoader.java:326)
        at workbench.gui.dbobjects.objecttree.DbObjectsTree.load(DbObjectsTree.java:447)
        at workbench.gui.dbobjects.objecttree.DbTreePanel$4.run(DbTreePanel.java:362)

2019-09-02 21:15:20 ERROR DbMetadata.getSchemas() WbWin-1 TAB-8: Error retrieving schemas: Not implemented Not implemented
java.lang.UnsupportedOperationException: Not implemented
        at io.burt.athena.AthenaDatabaseMetaData.getSchemas(AthenaDatabaseMetaData.java:662)
        at workbench.db.DbMetadata.getSchemas(DbMetadata.java:2794)
        at workbench.gui.dbobjects.objecttree.TreeLoader.loadSchemas(TreeLoader.java:412)
        at workbench.gui.dbobjects.objecttree.TreeLoader.load(TreeLoader.java:336)
        at workbench.gui.dbobjects.objecttree.DbObjectsTree.load(DbObjectsTree.java:447)
        at workbench.gui.dbobjects.objecttree.DbTreePanel$4.run(DbTreePanel.java:362)

2019-09-02 21:15:20 DEBUG DbMetadata.getSchemas() WbWin-1 TAB-8: Retrieving 0 schemas using getSchemas() took 0ms
2019-09-02 21:15:20 DEBUG TreeLoader.loadSchemas() Loaded 0 schemas. Currently selected types: [PROCEDURE, TABLE, TRIGGER, VIEW]
2019-09-02 21:15:24 DEBUG SqlPanel.runSelectedStatement() Selection length: 8, offset: 0, total length: 9
2019-09-02 21:15:24 WARN  SqlCommand.setMaxRowsForStatement() The JDBC driver does not support the setMaxRows() function! (Not implemented)
2019-09-02 21:16:26 ERROR SelectCommand.execute() Error executing:
SELECT 1
   java.util.concurrent.TimeoutException
java.sql.SQLTimeoutException: java.util.concurrent.TimeoutException
        at io.burt.athena.AthenaStatement.execute(AthenaStatement.java:83)
        at io.burt.athena.AthenaStatement.executeQuery(AthenaStatement.java:65)
        at workbench.sql.commands.SelectCommand.execute(SelectCommand.java:131)
        at workbench.sql.StatementRunner.runStatement(StatementRunner.java:552)
        at workbench.gui.sql.SqlPanel.displayResult(SqlPanel.java:3468)
        at workbench.gui.sql.SqlPanel.runStatement(SqlPanel.java:2199)
        at workbench.gui.sql.SqlPanel$16.run(SqlPanel.java:2137)
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at io.burt.athena.AthenaStatement.startQueryExecution(AthenaStatement.java:98)
        at io.burt.athena.AthenaStatement.execute(AthenaStatement.java:76)
        ... 6 more

**Comment by iconara** [comment]
There is unfortunately not much I can do with this information. I think I understand what you're trying to say since you opened another issue with some more context – but please give more context than just a stack trace.

The [readme explains what `UnsupportedOperationException` means](https://github.com/burtcorp/athena-jdbc#limitations--known-issues).
